add_newline = true


[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
format = "$symbol "

[line_break]
disabled = true

[directory]
truncation_length = 20
truncation_symbol = "…/"
truncate_to_repo = false
style = "bold cyan"
read_only_style = "bold red"
format = "[](bold blue) [$path]($style)[$read_only]($read_only_style) "

[python]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true
