vim.opt.mouse = 'a' -- enables the mouse
vim.opt.number = true -- enables numbers
vim.opt.relativenumber = true -- enables relative numbers
vim.opt.cursorline = true -- highlights the current line
vim.opt.cursorlineopt = 'both'
vim.opt.hlsearch = true -- highlights the searched word
vim.opt.ignorecase = true -- ignores the case of the searched word
vim.opt.smartcase = true -- if you search a word with capital case, lower case is ignored
vim.opt.tabstop = 4 -- the space for tabstops
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true -- uses spaces instead of tab characters
vim.opt.autoindent = true -- autoindents the code
vim.opt.wrap = false -- the code does not wrap around the screen
vim.opt.signcolumn = 'yes'
vim.opt.scrolloff = 3 -- the number of lines before the screen starts to scroll
