vim.cmd('set mouse=a')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set cursorline')

vim.cmd('set cursorlineopt=both')
vim.cmd('set hlsearch')
vim.cmd('set ignorecase')
vim.cmd('set smartcase')
vim.cmd('set tabstop=4')
vim.cmd('set softtabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set expandtab')
vim.cmd('set autoindent')
vim.cmd('set nowrap')
vim.cmd('set signcolumn=yes')
