import = ["/home/michael/.config/alacritty/tokyo-night.toml"]
live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Medium"

[window]
dynamic_title = true
#gtk_theme_variant = "dark"
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
lines = 31
columns = 130

[window.class]
general = "Alacritty"
instance = "Alacritty"

