add_newline = true

[character]
success_symbol = "[>](#04a5e5)"
error_symbol = "[>](red)"
format = "$symbol "

[line_break]
disabled = false

[directory]
truncation_length = 20
truncation_symbol = "…/"
truncate_to_repo = false
style = "bold #179299"
read_only_style = "bold red"
format = "[ ](#7287fd)[$path]($style)[$read_only]($read_only_style) "

[python]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true
